### ISSUE TITLE
Password prompts

### ISSUE THREAD

**Issue by pirone2** [thadunge2/AIDungeon#73] opened 2019-12-31 02:22 UTC
When playing the game after manually fixing the "missing parenthesis" crash, the input box works like a password box and doesn't show what you're typing.

It only happens when it's actually waiting for input, ie: doesn't happen while the game is initializing until it asks for new or load game
Editing the box element and making it a "text" instead of "password" only fixes it until it asks your next input.

I suspect it might be related to the newly commited encryption feature since it uses passwords, but it might have nothing to do with it.

**Comment by pirone2** [comment] 2019-12-31 02:27
Ah, and of course, apparently it's just a visual thing, the obscured commands and inputs seem to work normally.

**Comment by pirone2** [comment] 2019-12-31 03:13
Oh, found something new about it.
The text shows normally while it's processing an input.
Like:
->You type and send something in password format
->While it's processing you type whatever in the box and it shows normally
->When it stops processing and gives you its output your typed normal text becomes password format again

**Comment by machiavel23** [comment] 2019-12-31 17:55
https://github.com/cloveranon/Clover-Edition/issues/39#issuecomment-569966313

**Comment by RyushoYosei** [comment] 2020-01-01 12:01
Yeah I'm having this issue now myself .

**Comment by irregarde** [comment] 2020-01-01 22:28
I'm also having this issue.  When I manually change the widget element to "text," it's reset to "password" after one input.  My current browser is Chrome v. 81.0.4014.0 (Official Build) canary (64-bit).

**Comment by machiavel23** [comment] 2020-01-02 02:28
The problem is cause by a module named readline. We had a hard time with clover figuring it out. the best you can do for now on thadunge edition until he removes it from his fork is to manually edit some .py files (at least utils.py and play.py) to remove any readline import. You can easily do it with colab file editor, and can spot where are the readline lines by checking the commits on clover's github.

**Comment by thadunge2** [comment] 2020-01-03 02:51
Fixed by #76

**Closed as completed by thadunge2** 2020-01-03 02:51 UTC
